# This file was generated by GoReleaser. DO NOT EDIT.
cask "spm" do
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_darwin_amd64.tar.gz"
      sha256 "2639880f89ca3c84adfd671015e4439b32a13300971115887b6e727cdc0e3875"
    end
    on_arm do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_darwin_arm64.tar.gz"
      sha256 "fd3285b107f9d4622f160085e85c7ec14b22fb9dfae3d1b5e80527efe726e6ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_linux_amd64.tar.gz"
      sha256 "42b1da1c1b308a415140063aabfb9472d1db098276a49abbf7e638cc347e2cd7"
    end
    on_arm do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_linux_arm64.tar.gz"
      sha256 "1cca7917559ab0d1746c57aa0f13e3a6c215f532fa57b641dc9c32f3d63f1d51"
    end
  end

  name "spm"
  desc "Skills Package Manager for AI agents"
  homepage "https://skillpkg.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spm"

  # No zap stanza required

end
