# This file was generated by GoReleaser. DO NOT EDIT.
cask "spm" do
  version "1.2.1"

  on_macos do
    on_intel do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_darwin_amd64.tar.gz"
      sha256 "949b230b3eb99d558e1664a8bc31372ed75a3179b3d19dbf62f7d25911acfe5d"
    end
    on_arm do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_darwin_arm64.tar.gz"
      sha256 "6359f8d3bd2b6e70e62a25535230afa58770551a6c986496afa123a951424740"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_linux_amd64.tar.gz"
      sha256 "85004777acbcb9dc6a7440c2ab9646e8f3b899cb4f8720524277bf31b6464609"
    end
    on_arm do
      url "https://github.com/skillpkg/spm/releases/download/v#{version}/spm_#{version}_linux_arm64.tar.gz"
      sha256 "200ea8f80844dfdc404fd06d70bfeea72a7b5b674eed7d4110d746ed41aae6cc"
    end
  end

  name "spm"
  desc "Skills Package Manager for AI agents"
  homepage "https://skillpkg.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spm"

  # No zap stanza required

end
