# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spm < Formula
  desc "Skills Package Manager for AI agents"
  homepage "https://skillpkg.dev"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skillpkg/spm/releases/download/v1.2.2/spm_1.2.2_darwin_amd64.tar.gz"
      sha256 "27d87984064cda928addda17aa325ecb124ffb4055085a601ea37119e7738e8c"

      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skillpkg/spm/releases/download/v1.2.2/spm_1.2.2_darwin_arm64.tar.gz"
      sha256 "a5bfbd46adc4c0695770ad6db7e87d92f6925c6d30b29cc64d732a1c05dbf590"

      define_method(:install) do
        bin.install "spm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.2.2/spm_1.2.2_linux_amd64.tar.gz"
      sha256 "94ff8298d2396cdf5288a58a6e0aa357433dafe260102804683e2aa827edd59b"
      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.2.2/spm_1.2.2_linux_arm64.tar.gz"
      sha256 "6a562bbd51bc4e9282c0b58699fcdc382501228a11674b7a1dd633ba7e9fcfde"
      define_method(:install) do
        bin.install "spm"
      end
    end
  end
end
