# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spm < Formula
  desc "Skills Package Manager for AI agents"
  homepage "https://skillpkg.dev"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.3/spm_1.1.3_darwin_amd64.tar.gz"
      sha256 "4e410a2d9b865d312706d62f02b3e2d72b4ed2df371d3b2bc93f72c71c60c740"

      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.3/spm_1.1.3_darwin_arm64.tar.gz"
      sha256 "14d9778817c9781dcde85d81fef351513cac193e0e33c8feffab3baca08e264f"

      define_method(:install) do
        bin.install "spm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.3/spm_1.1.3_linux_amd64.tar.gz"
      sha256 "f557c9251832a8a87720d72abac8a0e46e623c856f90eb95f7d91b625ccd90ee"
      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.3/spm_1.1.3_linux_arm64.tar.gz"
      sha256 "ab8cbe624e0009cfda5a8d0e6be301402c7a68a80ec423ae1c14eaecf383ed40"
      define_method(:install) do
        bin.install "spm"
      end
    end
  end

  test do
    system "#{bin}/spm", "--version"
  end
end
