# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spm < Formula
  desc "Skills Package Manager for AI agents"
  homepage "https://skillpkg.dev"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.0/spm_1.1.0_darwin_amd64.tar.gz"
      sha256 "5673cf7e3e2270b43e0251a07f91a2487a531dac71bcb3052fb4c027f42a447c"

      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.0/spm_1.1.0_darwin_arm64.tar.gz"
      sha256 "b704cda191351ebe95da6eeb42da35adcf8606d3a35d3336ccd5aa2f8a29561e"

      define_method(:install) do
        bin.install "spm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.0/spm_1.1.0_linux_amd64.tar.gz"
      sha256 "af3b50a69f1c4a2c38c6f3205493e4946241893a735460e83d692a4dac5e338a"
      define_method(:install) do
        bin.install "spm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skillpkg/spm/releases/download/v1.1.0/spm_1.1.0_linux_arm64.tar.gz"
      sha256 "df9275eaba18c6bfa944daa8b77f53e684e170507df8cc5fbb9735b94623a45d"
      define_method(:install) do
        bin.install "spm"
      end
    end
  end

  test do
    system "#{bin}/spm", "--version"
  end
end
